# Generated by Django 4.0.2 on 2022-02-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='vehicle_make_model',
            field=models.CharField(default='', max_length=64),
        ),
    ]
