# Generated by Django 4.0.2 on 2022-02-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_person_email_person_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='vehicle_make_model',
            new_name='vehicle_make',
        ),
        migrations.AddField(
            model_name='person',
            name='vehicle_color',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='vehicle_model',
            field=models.CharField(default='', max_length=64),
        ),
    ]
